<<<<<<< HEAD
# Dependencies
markdown:         rdiscount
highlighter:      pygments

#
encoding:         "utf-8"
# Permalinks
permalink:        pretty
=======
title: Steve Yang
description: 杨海明的博客

url: http://yanghaiming.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/
>>>>>>> origin/master

# Setup
title:            Steve Yang
tagline:          'We are infinite.'
description:      'Thoughts and writings by Steve Yang.'
url:              http://yanghaiming.com

<<<<<<< HEAD
author:
  name:           'SteveYang'
  url:            https://github.com/Haiming-Yang

paginate:         5

# Custom vars
version:          1.0.0

# duoshuo
comments :
    provider : duoshuo
    duoshuo :
      short_name : yhm
=======
navigation:
 - title: Home
   url: /index.html
 - title: Posts
   url: /posts
 - title: About
   url: /about
 

social:
   github: SteveYang
   Weiobo: yhmshh
   Renren: 杨海明
   email: yhm1996@yahoo.com

google_analytics: ""
>>>>>>> origin/master
