# Dependencies
markdown:         rdiscount
highlighter:      pygments

#
encoding:         "utf-8"
# Permalinks
permalink:        pretty

# Setup
title:            Steve Yang
tagline:          'We are infinite.'
description:      'Thoughts and writings by Steve Yang.'
url:              http://yanghaiming.com

author:
  name:           'SteveYang'
  url:            https://github.com/Haiming-Yang

paginate:         5

# Custom vars
version:          1.0.0

# duoshuo
comments :
    provider : duoshuo
    duoshuo :
      short_name : yhm
